spring.application.name=vinicius
spring.datasource.url= jdbc:postgresql://localhost:5432/vinicius
spring.datasource.username=vinicius
spring.datasource.password=Hutlun2021!
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.profiles.active=test

spring.jpa.open-in-view=false

spring.mvc.pathmatch.matching-strategy=ant-path-matcher